version: '2'

services:
    certbot:
        image: certbot/certbot
        hostname: certbot
        container_name: certbot
        restart: unless-stopped
        volumes:
            - ./private/letsencrypt:/etc/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"

    nginx:
        build: ./config/nginx
        hostname: nginx
        container_name: nginx
        image: paskal/nginx-pagespeed:latest
        restart: unless-stopped
        command: /usr/sbin/nginx -g "daemon off;"
        volumes:
            - ./tmp:/home/admin/tmp
            - ./web/dev.favor-group.ru:/home/admin/web/dev.favor-group.ru
            - ./web/favor-group.ru:/home/admin/web/favor-group.ru
            - ./private/letsencrypt:/home/admin/private/letsencrypt
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/status.conf:/etc/nginx/conf.d/status.conf
            - ./config/nginx/server_name.conf:/home/admin/config/nginx/server_name.conf
            - ./config/nginx/pagespeed.conf:/etc/nginx/conf.d/pagespeed.conf
            - ./conf/web/dev.favor-group.ru.nginx.ssl.conf:/etc/nginx/conf.d/dev.favor-group.ru.nginx.ssl.conf
            - ./conf/web/https.redirect.nginx.conf:/etc/nginx/conf.d/https.redirect.nginx.conf
            - ./conf/web/favor-group.ru.nginx.ssl.conf:/etc/nginx/conf.d/favor-group.ru.nginx.ssl.conf
            - /tmp/favor-logs/:/var/log/nginx/domains/
        ports:
            - "9080:80"
            - "9443:443"
        environment:
            - TZ=Europe/Moscow

    percona-server:
        image: percona/percona-server:8.0
        hostname: percona-server
        container_name: percona-server
        restart: always
        # MYSQL_ROOT_PASSWORD, MYSQL_USER, MYSQL_PASSWORD
        env_file: private/environment/percona.env
        expose:
            - "3306"
        # TODO: remove after migration of app into docker
        ports:
            - "13306:3306"
        volumes:
            - ./config/percona/favor-group.cnf:/etc/my.cnf.d/favor-group.cnf
            # Data persistence
            - ./private/percona-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: admin_favorgroup
            TZ: Europe/Moscow
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    adminer:
        image: adminer:fastcgi
        hostname: adminer
        container_name: adminer
        restart: always
        expose:
            - "9000"

    # Percona Monitoring and Management client
    pmm-client:
        image: perconalab/pmm-client:2
        hostname: favor-group.ru
        container_name: pmm-client
        # depends_on section is needed if you're monitoring DB that is running in the docker-compose
        depends_on:
            - percona-server
        volumes:
            - ./private/pmm/pmm-agent.yaml:/etc/pmm-agent.yaml
        ports:
            - "42000:42000"
            - "42001:42001"

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        environment:
            - PMM_AGENT_CONFIG_FILE=/etc/pmm-agent.yaml
