version: '2'

services:
    certbot:
        image: certbot/certbot
        hostname: certbot
        container_name: certbot
        restart: unless-stopped
        volumes:
            - ./config/letsencrypt:/etc/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"

    percona-server:
        image: percona:8
        hostname: percona-server
        container_name: percona-server
        restart: always
        # MYSQL_ROOT_PASSWORD, MYSQL_USER, MYSQL_PASSWORD
        env_file: docker/environment/percona.env
        expose:
            - "3306"
        # TODO: remove after migration of app into docker
        ports:
            - "13306:3306"
        volumes:
            - ./config/percona/favor-group.cnf:/etc/my.cnf.d/favor-group.cnf
            # Data persistence
            - ./docker/percona-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_HOST: localhost
            MYSQL_DATABASE: admin_favorgroup

    adminer:
        image: adminer:fastcgi
        hostname: adminer
        container_name: adminer
        restart: always
        expose:
            - "9000"

    # Percona Monitoring and Management client
    pmm-client:
        image: perconalab/pmm-client:2
        hostname: favor-group.ru
        container_name: pmm-client
        # depends_on section is needed if you're monitoring DB that is running in the docker-compose
        depends_on:
            - percona-server
        volumes:
            - ./docker/pmm/pmm-agent.yaml:/etc/pmm-agent.yaml
        ports:
            - "42000:42000"
            - "42001:42001"

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        environment:
            - PMM_AGENT_CONFIG_FILE=/etc/pmm-agent.yaml

#    https://github.com/extremeshok/docker-nginx-pagespeed
#    nginx:
#        image: nginx:1.15-alpine
#        restart: unless-stopped
#        volumes:
#            - ./data/nginx:/etc/nginx/conf.d
#            - ./data/certbot/conf:/etc/letsencrypt
#            - ./data/certbot/www:/var/www/certbot
#        ports:
#            - "80:80"
#            - "443:443"
#        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
