version: '2'

services:
    certbot:
        image: certbot/certbot
        hostname: certbot
        container_name: certbot

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: unless-stopped
        volumes:
            - ./private/letsencrypt:/etc/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"

    nginx:
        build: ./config/nginx
        hostname: nginx
        container_name: nginx
        image: paskal/nginx-pagespeed:latest

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: unless-stopped
        depends_on:
            - adminer
            - php
        volumes:
            - ./web/dev.favor-group.ru:/web/dev.favor-group.ru
            - ./web/favor-group.ru:/web/favor-group.ru
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/bitrix.conf:/etc/nginx/bitrix.conf:ro
            - ./config/nginx/server_name.conf:/etc/nginx/server_name.conf:ro
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./private/letsencrypt:/etc/nginx/letsencrypt:ro
            # Logs
            - ./logs/nginx/:/var/log/nginx/
        ports:
            - "80:80"
            - "443:443"
        environment:
            - TZ=Europe/Moscow

    php:
        build: ./config/php-fpm
        image: paskal/bitrix-php:latest
        hostname: php
        container_name: php

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        expose:
            - "9000"
        volumes:
            - ./web/dev.favor-group.ru:/web/dev.favor-group.ru
            - ./web/favor-group.ru:/web/favor-group.ru
            - ./private/msmtprc:/etc/msmtprc
            - ./config/php-fpm/90-php.ini:/etc/php/7.4/fpm/conf.d/90-php.ini
            - ./config/php-fpm/90-php.ini:/etc/php/7.4/cli/conf.d/90-php.ini
            # BX_TEMPORARY_FILES_DIRECTORY in bitrix/php_interface/dbconn.php
            - /tmp/favor-group.ru/:/tmp/favor-group.ru/
            - /tmp/dev.favor-group.ru/:/tmp/dev.favor-group.ru/
            # MySQL socket to prevent transferring data trough TCP
            - /var/run/mysqld/:/var/run/mysqld/
            # Logs
            - ./logs/php:/var/log/php
        depends_on:
            - mysql
            - memcached

    php-cron:
        command: cron && tail -f /var/log/cron.log
        image: paskal/bitrix-php:latest
        hostname: php-cron
        container_name: php-cron

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        volumes:
            - ./web/dev.favor-group.ru:/web/dev.favor-group.ru
            - ./web/favor-group.ru:/web/favor-group.ru
            - ./private/msmtprc:/etc/msmtprc
            - ./config/php-fpm/90-php.ini:/etc/php/7.4/fpm/conf.d/90-php.ini
            - ./config/php-fpm/90-php.ini:/etc/php/7.4/cli/conf.d/90-php.ini
            # BX_TEMPORARY_FILES_DIRECTORY in bitrix/php_interface/dbconn.php
            - /tmp/favor-group.ru/:/tmp/favor-group.ru/
            - /tmp/dev.favor-group.ru/:/tmp/dev.favor-group.ru/
            # MySQL socket to prevent transferring data trough TCP
            - /var/run/mysqld/:/var/run/mysqld/
            # Cronjobs
            - ./config/cron/tasks.cron:/etc/cron.d/tasks:ro
            # Logs
            - ./logs/php:/var/log/php
            - ./logs/cron:/var/log/cron
        depends_on:
            - mysql
            - memcached

    mysql:
        image: percona/percona-server:8.0
        hostname: mysql
        container_name: mysql

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        # MYSQL_ROOT_PASSWORD, MYSQL_USER, MYSQL_PASSWORD
        env_file: private/environment/mysql.env
        expose:
            - "3306"
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            # Configuration
            - ./config/mysql/my.cnf:/etc/my.cnf.d/my.cnf
            # Data persistence
            - ./private/mysql-data:/var/lib/mysql
            # MySQL socket to prevent transferring data trough TCP
            # do chmod user:1001 /var/run/mysqld/
            - /var/run/mysqld/:/var/mysql-socket/
            # Logs
            - ./logs/mysql:/var/log/mysql
        environment:
            MYSQL_DATABASE: admin_favorgroup
            TZ: Europe/Moscow
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    memcached:
        image: memcached:1-alpine
        hostname: memcached
        container_name: memcached
        expose:
            - "11211"

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

    adminer:
        image: adminer
        hostname: adminer
        container_name: adminer
        depends_on:
            - mysql
        expose:
            - "8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always

    ftp:
        image: stilliard/pure-ftpd
        container_name: ftp
        # FTP_USER_NAME, FTP_USER_PASS
        env_file: private/environment/ftp.env
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - ./web/favor-group.ru:/home/web
            - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
        environment:
            PUBLICHOST: "favor-group.ru"
            FTP_USER_HOME: /home/web

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always

    # Monitoring

    ## Percona Monitoring and Management client
    pmm-client:
        image: percona/pmm-client:2
        hostname: favor-group.ru
        container_name: pmm-client
        depends_on:
            - mysql
        volumes:
            # Configuration, should be generated using that doc:
            # https://gist.github.com/paskal/48f10a0a584f4849be6b0889ede9262b
            - ./private/pmm/pmm-agent.yaml:/etc/pmm-agent.yaml
            # MySQL socket to prevent transferring data trough TCP
            - /var/run/mysqld/:/var/run/mysqld/
        ports:
            - "42000:42000"
            - "42001:42001"

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        restart: always
        environment:
            - PMM_AGENT_CONFIG_FILE=/etc/pmm-agent.yaml

    ## Zabbix Agent 2
    zabbix-agent:
        image: zabbix/zabbix-agent2:latest
        container_name: zabbix-agent
        restart: always
        privileged: true
        depends_on:
            - mysql
            - nginx
        # temporary, remove after moving from Debian to Ubuntu where it would be possible
        # to set proper permissions for container user for /var/run/docker.sock
        # user: root

        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

        volumes:
            # this is needed in order to monitor docker
            # to make it work you need to create user "zabbix" with id 1997 on the host system,
            # and make sure it has enough permissions to read /var/run/docker.sock
            - /var/run/docker.sock:/var/run/docker.sock

        environment:
            - TZ=Europe/Moscow
            - ZBX_HOSTNAME=favor-group.ru.docker
            - ZBX_SERVER_HOST=zabbix.terrty.net,46.101.10.22
